language: go

env:
- GO111MODULE=on

go:
- 1.13.x

jobs:
  include:
    - stage: lint
      script: docker build -t lint -f build/docker/linter/Dockerfile .
    - stage: test
      script: go test -v -cpu=1,2 ./...
    - stage: coverage
      script: ./coverage.sh
